# Generated by Django 4.0.2 on 2022-03-27 23:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movement Reason',
            },
        ),
        migrations.CreateModel(
            name='MoveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movement Type',
            },
        ),
        migrations.CreateModel(
            name='TimeSpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Time Spending',
            },
        ),
        migrations.CreateModel(
            name='MovementPass',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_m', models.CharField(max_length=200, null=True, verbose_name='From Where')),
                ('to_m', models.CharField(max_length=200, null=True, verbose_name='To Where')),
                ('sub_dristrict', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Dristrict Name')),
                ('date', models.DateTimeField()),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.district', verbose_name='District Name')),
                ('move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.movetype')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.movementreason')),
                ('time_spand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.timespend')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.passuser')),
            ],
            options={
                'verbose_name': 'Movement Pass',
                'verbose_name_plural': 'Movement Pass',
            },
        ),
    ]
